
function lsp_ceoff_config(this_block)

  % Revision History:
  %
  %   17-Jun-2014  (18:02 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/aruls/projects/phd/g729/design/lsp/lsp_ceoff.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('lsp_ceoff');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('sys_rst_n');
  this_block.addSimulinkInport('aff_data_count');
  this_block.addSimulinkInport('aff_data_full');
  this_block.addSimulinkInport('aff_data_empty');
  this_block.addSimulinkInport('aff_read_data');

  this_block.addSimulinkOutport('lsp_read_en');
  this_block.addSimulinkOutport('lsp_audio_sample');

  lsp_read_en_port = this_block.port('lsp_read_en');
  lsp_read_en_port.setType('UFix_1_0');
  lsp_read_en_port.useHDLVector(false);

  lsp_audio_sample_port = this_block.port('lsp_audio_sample');
  lsp_audio_sample_port.setType('XFloat_8_24');


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('sys_rst_n').width ~= 1);
      this_block.setError('Input data type for port "sys_rst_n" must have width=1.');
    end

    this_block.port('sys_rst_n').useHDLVector(false);

    % (!) Port 'aff_data_count' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    if (this_block.port('aff_data_count').width ~= 10);
      this_block.setError('Input data type for port "aff_data_count" must have width=10.');
    end

    if (this_block.port('aff_data_full').width ~= 1);
      this_block.setError('Input data type for port "aff_data_full" must have width=1.');
    end

    this_block.port('aff_data_full').useHDLVector(false);

    if (this_block.port('aff_data_empty').width ~= 1);
      this_block.setError('Input data type for port "aff_data_empty" must have width=1.');
    end

    this_block.port('aff_data_empty').useHDLVector(false);

    % (!) Port 'aff_read_data' appeared to have dynamic type in the HDL -- please add type checking as appropriate;
    if (this_block.port('aff_read_data').width ~= 32);
      this_block.setError('Input data type for port "aff_data_count" must have width=10.');
    end

  % (!) Port 'lsp_audio_sample' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'sys_clk','sys_ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('RAM_ADDR_WIDTH','integer','10');
  this_block.addGeneric('RAM_DATA_WIDTH','integer','32');
  %this_block.addGeneric('lsp_msm_idle','integer','1');
  %this_block.addGeneric('lsp_msm_read_from_fifo','integer','2');
  %this_block.addGeneric('lsp_msm_calc_lsp_coeff','integer','4');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../lsp/lsp_ceoff.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

